### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by shuttle1987** [JamesDevJim/game-zulu#2]
For example there's some code that is commented out and seemingly duplicated here:

https://github.com/JamesDevJim/game-zulu/blob/4b46243499803992d0ef07bb856fb49bb8f72240/game_changer.py#L8-L18

Since we are using Git+Github we can delete these lines and use Git directly if we require a backup in the future.

**Comment by JamesDevJim** [comment]
Thanks. Good idea.

**Comment by JamesDevJim** [comment]
Thanks for removing these lines of dead code.
